
stages:
  - build

release:
  stage: release
  image : docker:latest
  tags: [docker]
  services:
    - docker:dind
  environment:
    name: Development
  cache:
    key: my-cache
    paths:
      -  node_modules
  variables:
    DOCKER_TLS_CERTDIR: ""

  script:
      -  docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      -  docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
      -  docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
      